import os

from decouple import config, Csv

SOURCE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SOURCE_DIR)

OUPUT_MEDIA_SERVER_URL = config('OUPUT_MEDIA_SERVER_URL', default='rtmp://localhost/hls/')

REDIS_ADDRESS = config('REDIS_ADDRESS', default='localhost')
REDIS_PORT = config('REDIS_PORT', default='6379')

TRACER_REPORTING_HOST = config('TRACER_REPORTING_HOST', default='localhost')
TRACER_REPORTING_PORT = config('TRACER_REPORTING_PORT', default='6831')

SERVICE_STREAM_KEY = config('SERVICE_STREAM_KEY')

LISTEN_EVENT_TYPE_QUERY_CREATED = config('LISTEN_EVENT_TYPE_QUERY_CREATED')
LISTEN_EVENT_TYPE_QUERY_REMOVED = config('LISTEN_EVENT_TYPE_QUERY_REMOVED')

SUPPORTED_VIDEO_OUTPUT_TYPES = config('SUPPORTED_VIDEO_OUTPUT_TYPES', cast=Csv())

SERVICE_CMD_KEY_LIST = [
    LISTEN_EVENT_TYPE_QUERY_CREATED,
    LISTEN_EVENT_TYPE_QUERY_REMOVED
]


PUB_EVENT_LIST = [
]

# Only for Content Extraction services
SERVICE_DETAILS = None

LOGGING_LEVEL = config('LOGGING_LEVEL', default='DEBUG')

DEFAULT_FFMPEG_BIN_PATH = os.path.join(PROJECT_ROOT, 'ffmpeg_bin', 'ffmpeg-linux64-v3.3.1')
FFMPEG_BIN = config('FFMPEG_BIN', default=DEFAULT_FFMPEG_BIN_PATH)

DEFAULT_VIDEO_STREAMER_SCRIPT_PATH = os.path.join(
    SOURCE_DIR, 'video_streaming', 'query_video_streamer.py')
VIDEO_STREAMER_SCRIPT =  config('VIDEO_STREAMER_SCRIPT', default=DEFAULT_VIDEO_STREAMER_SCRIPT_PATH)

DEFAULT_VIDEO_STREAMER_PIPE_SCRIPT_PATH = os.path.join(
    SOURCE_DIR, 'video_streaming', 'video_stream.sh')
VIDEO_STREAMER_PIPE_SCRIPT =  config('VIDEO_STREAMER_PIPE_SCRIPT', default=DEFAULT_VIDEO_STREAMER_PIPE_SCRIPT_PATH)